---
- name: "update apt packages"
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: true

- name: "install dependecies"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "indstall pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present