---
- name: "update apt packages"
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: true

- name: "install node & npm."
  become: true
  ansible.builtin.shell: |
    curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
    apt-get install -y nodejs

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present