---
- name: "ensure backend dir exists"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "unarchive artifacts"
  become: true
  ansible.builtin.unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "start the server"
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start