version: 2.1

executors:
  docker-node-executor:
    docker:
      - image: circleci/node:13.8.0

jobs:
  build-frontend:
    executor: docker-node-executor
    steps:
      - checkout
      - run: |
          cd frontend
          npm install
          npm run build

workflows:
  my-custom-workflow:
    jobs:
      - build-frontend